version: "3"

networks:
  app-tier:
    driver: bridge

services:

  kafka:
    image: bitnami/kafka:3.4.1
    container_name: kafka
    networks:
      - app-tier
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_MESSAGE_MAX_BYTES: 1000000
    healthcheck:
      test: ["CMD-SHELL", "if [[ $$(kafka-topics.sh --list  --bootstrap-server kafka:9092) != *'Error'* ]]; then exit 0; fi"]
      interval: 20s
      timeout: 20s
      retries: 5

  producer:
    container_name: producer
    networks:
      - app-tier
    build:
      context: cryptocom-stream-producer/
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
